(SELECT '1Q' AS QUARTER, COUNT(*) AS ECOLI_COUNT FROM ECOLI_DATA WHERE (MONTH(DIFFERENTIATION_DATE) = 01 OR MONTH(DIFFERENTIATION_DATE) = 02 OR MONTH(DIFFERENTIATION_DATE) = 03) 
UNION ALL 
SELECT '2Q' AS QUARTER, COUNT(*) AS ECOLI_COUNT FROM ECOLI_DATA WHERE (MONTH(DIFFERENTIATION_DATE) = 04 OR MONTH(DIFFERENTIATION_DATE) = 05 OR MONTH(DIFFERENTIATION_DATE) = 06)
UNION ALL
SELECT  '3Q' AS QUARTER, COUNT(*) AS ECOLI_COUNT FROM ECOLI_DATA WHERE (MONTH(DIFFERENTIATION_DATE) = 07 OR MONTH(DIFFERENTIATION_DATE) = 08 OR MONTH(DIFFERENTIATION_DATE) = 09)
UNION ALL
SELECT '4Q' AS QUARTER, COUNT(*) AS ECOLI_COUNT FROM ECOLI_DATA WHERE (MONTH(DIFFERENTIATION_DATE) = 10 OR MONTH(DIFFERENTIATION_DATE) = 11 OR MONTH(DIFFERENTIATION_DATE) = 12))
ORDER BY QUARTER ASC