-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE   from MEMBER_PROFILE A  LEFT JOIN REST_REVIEW  B ON A.MEMBER_ID = B.MEMBER_ID WHERE B.MEMBER_ID = (SELECT MEMBER_ID FROM REST_REVIEW GROUP BY MEMBER_ID ORDER BY COUNT(*) DESC LIMIT 1) order by REVIEW_DATE ASC, REVIEW_TEXT ASC
