-- SELECT INGREDIENT_TYPE FROM ICECREAM_INFO GROUP BY INGREDIENT_TYPE
SELECT INGREDIENT_TYPE, sum(TOTAL_ORDER) AS TOTAL_ORDER FROM FIRST_HALF A LEFT JOIN ICECREAM_INFO B ON A.FLAVOR = B.FLAVOR WHERE INGREDIENT_TYPE IN (SELECT INGREDIENT_TYPE FROM ICECREAM_INFO GROUP BY INGREDIENT_TYPE) GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC