-- 코드를 입력하세요
-- COUNT(*)
-- CATEGORY, COUNT(*) AS TOTAL_SALES 
SELECT CATEGORY, SUM(SALES) FROM BOOK A LEFT JOIN BOOK_SALES B ON A.BOOK_ID = B.BOOK_ID WHERE SALES_DATE LIKE '2022-01%' GROUP BY CATEGORY  ORDER BY CATEGORY